version: "3"

services:
  app:
    build: .
    container_name: next-js-base
    ports:
      - 3000:3000
    environment: 
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
    volumes:
      - .:/home/app